version: '3.8'
 
 
services:
  spark-kafka-reader:
    build:
      context: ..
      dockerfile: docker/Dockerfile.spark
    image: flight-data-spark:latest
    container_name: spark-kafka-reader
    ports:
      - "4040:4040"  # Spark Application UI
    command: >
      /opt/spark/bin/spark-submit
        --master local[*]
        --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.0,com.datastax.spark:spark-cassandra-connector_2.12:3.4.1
        --conf spark.sql.streaming.checkpointLocation=/tmp/checkpoints
        --conf spark.cassandra.connection.host=cassandra-1,cassandra-2,cassandra-3
        --conf spark.cassandra.connection.port=9042
        --conf spark.cassandra.connection.keepAliveMS=60000
        --conf spark.cassandra.auth.username=""
        --conf spark.cassandra.auth.password=""
        /app/kafka_reader.py
    restart: unless-stopped
    networks:
      - flight-network
 
networks:
  flight-network:
    external: true
    name: docker_flight-network