version: '3.8'
 
 
services:
  spark:
    build:
      context: ..
      dockerfile: docker/Dockerfile.spark
    image: flight-data-spark:latest
    container_name: spark
    ports:
      - "4040:4040"  # Spark Application UI
    command: >
      /opt/spark/bin/spark-submit
        --master local[4]
        --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.0,com.datastax.spark:spark-cassandra-connector_2.12:3.4.1,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
        --conf spark.sql.streaming.checkpointLocation=s3a://checkpoints/
        --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
        --conf spark.hadoop.fs.s3a.access.key=minioadmin
        --conf spark.hadoop.fs.s3a.secret.key=minioadmin123
        --conf spark.hadoop.fs.s3a.path.style.access=true
        --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
        --conf spark.hadoop.fs.s3a.connection.ssl.enabled=false
        --conf spark.cassandra.connection.host=cassandra-1,cassandra-2,cassandra-3
        --conf spark.cassandra.connection.port=9042
        --conf spark.cassandra.connection.keepAliveMS=60000
        --conf spark.cassandra.auth.username=cassandra
        --conf spark.cassandra.auth.password=cassandra
        /app/spark/reader.py
    restart: unless-stopped
    networks:
      - flight-network
    develop:
      watch:
        - action: sync
          path: ../spark
          target: /app/spark
          ignore:
            - __pycache__/
        - action: rebuild
          path: ../spark/reader.py
 
networks:
  flight-network:
    external: true
    name: docker_flight-network