apiVersion: v1
kind: Secret
metadata:
  name: spark-stream-secrets
  namespace: spark
type: Opaque
stringData:
  CASSANDRA_USERNAME: "cassandra"
  CASSANDRA_PASSWORD: "cassandra"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"
