server:
  workers: 1
coordinator:
  jvm:
    maxHeapSize: "2G"
  resources:
    limits:
      cpu: "2"
      memory: "3Gi"
    requests:
      cpu: "1"
      memory: "2Gi"
worker:
  jvm:
    maxHeapSize: "2G"
  resources:
    limits:
      cpu: "2"
      memory: "3Gi"
    requests:
      cpu: "1"
      memory: "2Gi"
catalogs:
  cassandra.properties: |
    connector.name=cassandra
    cassandra.contact-points=cassandra.default.svc.cluster.local
    cassandra.native-protocol-port=9042
    cassandra.load-policy.dc-aware.local-dc=dc1
    cassandra.consistency-level=ONE

service:
  type: NodePort