apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-data
  namespace: nifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-registry-data
  namespace: nifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
