apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  namespace: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - name: nifi
          image: custom-nifi-secure:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: https
          env:
            - name: SINGLE_USER_CREDENTIALS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nifi-credentials
                  key: NIFI_SINGLE_USER_USERNAME
            - name: SINGLE_USER_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nifi-credentials
                  key: NIFI_SINGLE_USER_PASSWORD
            - name: NIFI_SENSITIVE_PROPS_KEY
              valueFrom:
                secretKeyRef:
                  name: nifi-credentials
                  key: NIFI_SENSITIVE_PROPS_KEY
            - name: NIFI_WEB_HTTPS_HOST
              value: "0.0.0.0"
            - name: NIFI_WEB_HTTPS_PORT
              value: "8443"
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "1"
              memory: "3Gi"
          volumeMounts:
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/flowfile_repository
              subPath: flowfile_repository
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/content_repository
              subPath: content_repository
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/provenance_repository
              subPath: provenance_repository
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/database_repository
              subPath: database_repository
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/logs
              subPath: logs
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/state
              subPath: state
            - name: nifi-api-params
              mountPath: /opt/nifi/nifi-data/config
      volumes:
        - name: nifi-data
          persistentVolumeClaim:
            claimName: nifi-data
        - name: nifi-api-params
          configMap:
            name: nifi-api-params
