apiVersion: v1
kind: Secret
metadata:
  name: nifi-credentials
  namespace: nifi
type: Opaque
stringData:
  NIFI_SINGLE_USER_USERNAME: admin
  NIFI_SINGLE_USER_PASSWORD: Utlinhsaygex123.
  OPENSKY_CLIENT_SECRET: paHxSeaWLsaVrXDP0dT3cIkHYds8Top8
  NIFI_SENSITIVE_PROPS_KEY: nifi-sensitive-props-key-2026-change-me
