---
apiVersion: v1
kind: Secret
metadata:
  name: spark-secret
  namespace: spark
type: Opaque
stringData:
  # Cassandra credentials
  CASSANDRA_USERNAME: "cassandra"
  CASSANDRA_PASSWORD: "cassandra"
  # MinIO credentials
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"
